# Generated by Django 4.0.4 on 2023-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('date_release', models.DateField()),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
